#!/bin/sh
#------------------------------------------------------------------------------
# Configure the service. This script runs in docker container
#------------------------------------------------------------------------------
cat <<"EOF"
INFO: All is done! Try blow:
    PROXY_PORT=8999
    export http_proxy=127.0.0.1:$PROXY_PORT
    export https_proxy=127.0.0.1:$PROXY_PORT
    git config --global https.proxy https://127.0.0.1:$PROXY_PORT

    curl google.com
EOF

cd $(dirname $0)/..
/usr/sbin/privoxy --no-daemon privoxy/config 2>&1 >/dev/null &

start=$1
if [ "$start" = "daemon" ]; then
  sslocal -c ss/ss.json 2>&1 >/dev/null &
  sleep 2

elif [ "$start" = "down" ]; then
  export http_proxy=
  export https_proxy=
  git config --global https.proxy ''
else
  sslocal -c ss/ss.json
fi
